name: gtk_flutter
description: "Get to know Firebase with Flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.2.7
  firebase_core: ^3.8.0
  firebase_ui_auth: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png
