// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEElxyMo58aqVM9rUPJ5PUU_e4PascnMY',
    appId: '1:434692541240:web:82662926b9e3f32d954fcd',
    messagingSenderId: '434692541240',
    projectId: 'fir-flutter-codelab-32701',
    authDomain: 'fir-flutter-codelab-32701.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-32701.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjzO6AHX8o65Kq2VNNMNRE_QN2BkGwwk',
    appId: '1:434692541240:android:34f16a214b26a740954fcd',
    messagingSenderId: '434692541240',
    projectId: 'fir-flutter-codelab-32701',
    storageBucket: 'fir-flutter-codelab-32701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ntlpRbwkumI2jwbHI4hGsRLRkHwB600',
    appId: '1:434692541240:ios:f5b7d014588195fd954fcd',
    messagingSenderId: '434692541240',
    projectId: 'fir-flutter-codelab-32701',
    storageBucket: 'fir-flutter-codelab-32701.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ntlpRbwkumI2jwbHI4hGsRLRkHwB600',
    appId: '1:434692541240:ios:f5b7d014588195fd954fcd',
    messagingSenderId: '434692541240',
    projectId: 'fir-flutter-codelab-32701',
    storageBucket: 'fir-flutter-codelab-32701.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}


